### ISSUE TITLE
Method to Generate Point Cloud Fragments

### ISSUE THREAD

**Issue by XuyangBai** [zgojcic/3DSmoothNet#10]
Hi, Thanks for your sharing.  I have a little question.

In 3DMatch the author claimed that they are using 50 depth image to do TSDF  to get one point cloud fragment(.ply file). But I found the number of ply provided in their website geometric registration benchmark part does not equal to the rgbd images / 50. For example there are 10204 pairs of color images and depth images in `sun3d-hotel_uc-scan3` dataset, but only 54 ply files is provided in the geometric registration benchmark. So I wonder do they just use part of rgbd image to generate ply file or maybe I miss some information? Could you please explain a little bit how you generate the point cloud fragments ? Or can you share the code for generating the point cloud if you are not using the code from 3DMatch ?

Best,
Xuyang.

**Comment by zgojcic** [comment]
HI Xuyang, 

we just used the code from the 3DMatch (https://github.com/andyzeng/3dmatch-toolbox/tree/master/depth-fusion) to create the point clouds used for traning. For the testing we just downloaded the point clouds provided by the authors of 3DMatch. 

I think you should adress this question to the authors of 3DMatch.

Best

Zan

**Comment by XuyangBai** [comment]
Hi, Zan

I did the same way as yours but just find the number of fragments is different with what 3DMatch paper claimed. I will double check with the authors of 3DMatch.

Thanks.
Xuyang.
