### ISSUE TITLE
How to Generate Training Data TFRecorder

### ISSUE THREAD

**Issue by sherrygp** [zgojcic/3DSmoothNet#11]
Hi
    I test the pre-trained model in my lidar point cloud and the result is not good, but i do the process in my  rgbd point cloud ,the match result is perfect. I think i should finetune the pre-trained model in my lisdar data ,but i do not know how to generate the sample_training_file.tfrecord from the point cloud and transformation groudturth.Would it be convenient for you to tell me the process?
thanks

**Comment by zgojcic** [comment]
Hi,

so it could be that your parameters (mostly the size of the radius) are not appropriate for you LiDAR point cloud. We are actually using the pre-trained descriptor on LiDAR point clouds a lot and it works good. 

Anyway, to create the TFRecords we did the following:
1) Find point cloud with overlap 
2) Randomly sample X points from this overlap from PC1 and find their nearest neighbors in PC2 (after the ground truth transformation is applied). Here we also had a treshold that the distance between the nearest neighbors cannot be more than 1.5x times the mean resolution of the point clouds.
3) Compute the SDV voxel grid for both of them. 
4) Save them as tf_records. If you give me your email I can send you a small example code on how to save the data. 

Hope this helps. 

Best

zan

**Comment by sherrygp** [comment]
Hi
I send the Email to your adress.

**Comment by gachiemchiep** [comment]
Hello @zgojcic
I'm facing the same problem as sherrygp .
 i have sent the email to your address. 
Please send me that small example code. 
Thank you.

**Comment by gachiemchiep** [comment]
Hello @sherrygp 
Do you know how to solve this problem ?

**Comment by surabhi96** [comment]
Hi @zgojcic 
Can you send me this code to generate training data for the network? Also, how do you determine the overlap region from where to sample the keypoints? Thanks!

**Comment by zgojcic** [comment]
Hi surabhi96, 

example source code on how to create the tfrecords files is available [here](https://github.com/zgojcic/3DSmoothNet/blob/master/core/saveDataToTFrecordsExample.py)

Keypoints are randomly sampled from the whole point clouds not just the overlap, because we do not have the information about the overlap region.

**Comment by surabhi96** [comment]
Thanks for your reply @zgojcic
I am trying to run training with the 3DMatch dataset and that question was regarding generating data for the network. For that, I believe, I will have to generate keypoints in the overlap region and then determine correspondence? Having said that, is there code that I can use to take in rgbd/pcd/ply and give out the pairs of corresponding descriptors for the network input?

**Comment by zgojcic** [comment]
I am not sure I understand the quesiton, do you have the ground truth transformaiton matrix?
