### ISSUE TITLE
How do I get the keypoints.txt

### ISSUE THREAD

**Issue by libaosuan** [zgojcic/3DSmoothNet#12]
I have run the demo.py.I want to use my own point cloud data,but I don't know what is the keypoints.txt.

**Comment by sherrygp** [comment]
with open(traindata_path, "w") as f:
        for i in range(1000):
            index = np.random.randint(0, len(point_cloud_data))
            f.writelines(str(index))
            f.writelines('\n')

**Comment by libaosuan** [comment]
> ```
> with open(traindata_path, "w") as f:
>     for i in range(1000):
>         index = np.random.randint(0, len(point_cloud_data))
>         f.writelines(str(index))
>         f.writelines('\n')
> ```

sorry,I don't understand

**Comment by sherrygp** [comment]
Random Generation

**Comment by sherrygp** [comment]
traindata_path = 'cloud_bin_1_keypoints.txt'
    with open(traindata_path, "w") as f:
        for i in range(1000):
            index = np.random.randint(0, len(point_cloud_data))
            f.writelines(str(index))
            f.writelines('\n')

**Comment by libaosuan** [comment]
> traindata_path = 'cloud_bin_1_keypoints.txt'
> with open(traindata_path, "w") as f:
> for i in range(1000):
> index = np.random.randint(0, len(point_cloud_data))
> f.writelines(str(index))
> f.writelines('\n')

Ok ,I understand. Thank you!

**Comment by libaosuan** [comment]
> traindata_path = 'cloud_bin_1_keypoints.txt'
> with open(traindata_path, "w") as f:
> for i in range(1000):
> index = np.random.randint(0, len(point_cloud_data))
> f.writelines(str(index))
> f.writelines('\n')

the point_cloud_data is a matrix of point cloud x,y,z coordinate?
