### ISSUE TITLE
Demo.py only works on the given keypoints, method does not generalize well?

### ISSUE THREAD

**Issue by Guptajakala** [zgojcic/3DSmoothNet#13]
The keypoints file works always. However, when I change the the [keypoints part](https://github.com/zgojcic/3DSmoothNet/blob/06e8651472233ca26591ff84b3d82f7d64ac0ffa/main.cpp#L82) to randomly select 1000 indices: 

```
std::vector<int> ep_temp(cloud->points.size());
std::iota(ep_temp.begin(), ep_temp.end(), 0);
unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
std::shuffle(ep_temp.begin(), ep_temp.end(), std::default_random_engine(seed));
evaluation_points.insert(evaluation_points.begin(), ep_temp.begin(), ep_temp.begin()+1000);
ep_temp.clear();
```

This almost never works. Is there any other tricks to make it work?

**Comment by zgojcic** [comment]
Hi Guptajakala, 

the point are sampled randomly and there is no trick to make it work. We use 1000 keypoint in the example and 5000 keypoints in the paper for the evaluation. 

One possible reason that I can think of is that you are only changing the indices in the input parametrization file but are not saving them to text file which is then read by the python code for RANSAC.

(https://github.com/zgojcic/3DSmoothNet/blob/master/demo.py#L82) 

This way you compute the descriptors for your own indices but RANSAC thinks that they are actually other indices (the one in the files).

Could this be the reason?

**Comment by Guptajakala** [comment]
@zgojcic 
This perfectly solves the problem! Sorry about my careless. Thank you!
