### ISSUE TITLE
Bad result in final alignment 

### ISSUE THREAD

**Issue by Karltlbm** [zgojcic/3DSmoothNet#15]
Hi ! 

I have two pointclouds from lidar and photogrammetry acquisitions.
The result is null as no correspondence is found.

```
registration::RegistrationResult with fitness = 0.000000, inlier_rmse = 0.000000, and correspondence_set size of 0
Access transformation to get result.
```

The files are accessible here :
https://drive.google.com/file/d/1pxP_koE6FP5EjjnAvU_tJrFAbw2RprK3/view?usp=sharing
https://drive.google.com/file/d/1nVKukdgohvQdlay0ZwGA9mZCQMr6xVdq/view?usp=sharing

What do you think ?
Should I try to slightly align them first before using 3DSmoothNet ?

**Comment by zgojcic** [comment]
Hi,

I had a look at your data. First it has very little overlap with changes between the point clouds (in lidar point cloud there are a lot of cars parked on the street while in the photogrammetric there are none). 

However the main problem is the scale of the point clouds. The photogrametric one is not true to scale (the scale is ~0.8). 3DSmoothNet is not invariant to scale changes (we use an absolut voxel size and radius for the nn search). If you could consider the scale it should probably work. 

Also the registration pipeline in the demo.py does not estimate the scale but assumes that is one such that the registration parameters cannot be estimated correctly in your case.

**Comment by Karltlbm** [comment]
Thanks for your answer.

Yes the acquisitions were at diffrent time, hence the missing cars in the photogrammetry ... :)
Still we wanted to see if it works.
In the future, we will have GNSS positionning for the photoG acquisition so I guess we will have a scaled pointcloud.
In CloudCompare, they have a way to scale the pointclouds together while aligning them. But the alignment is done by clicking on common points.

I won't work on this project anymore.

Thanks a lot for your help and good work !
