### ISSUE TITLE
How to generate tfrecord using my own data

### ISSUE THREAD

**Issue by CaiStark** [zgojcic/3DSmoothNet#16]
Hi
I want to try it using my own data, but i donot know how to generate tfrecord.
Hope to get your help
thanks

**Comment by zgojcic** [comment]
Hi, 

I have added a small example file that shows how the tfRecords files can be generated. They just contain the SDV feature vector of the anchor point (X) and the corresponding point from another point cloud (Y). The negative examples are then sampled on the fly from all the positive ones. 

Best

Zan

**Comment by snoiarao** [comment]
Hi! 

I am trying to generate my own files using the saveDatatoTFRecord.py file. I am a little confused as to what is in mapped_indices.npz . I have a text file with indices of interest points for point clouds X and Y which was used for the initial input parametrization. Does mapped_indices.npz contain the actual point cloud values at each index, or is it the same index file of indices?
