### ISSUE TITLE
GPU for input parametrization 

### ISSUE THREAD

**Issue by snoiarao** [zgojcic/3DSmoothNet#17]
Hi! Is there a way to enable GPU services for the input parametrization step before inference? My system takes a while to compute the SDV grids for each keypoint, but I have 3 GPU cards available for use that could probably allow for much faster computation. Just wondering if this was something already available! Thanks

**Comment by caifazhou** [comment]
We do not have the GPU implementation for computing the SDV. We are glad to include it in the repository if you have the implementation.
