### ISSUE TITLE
mapped_indices in SaveDatatoTfRecord.py

### ISSUE THREAD

**Issue by snoiarao** [zgojcic/3DSmoothNet#26]
Hi!

Firstly, Thanks so much for creating this tool! I am still interested in using it in a project, and currently am hoping to fine tune the network on my own data. 

I am trying to generate my own files using the saveDatatoTFRecord.py file. I am a little confused as to what is in mapped_indices.npz . I have a text file with indices of interest points for point clouds X and Y which were used for the initial input parametrization via 3Dsmoothnet executable. Does mapped_indices.npz contain the actual point cloud values at each index, or is it the same index file of indices?

**Comment by zgojcic** [comment]
Hi,

mapped_indices.npz just contained the indices of the correspondences from each fragment. As we were creating one file per each scene it included multiple fragments and the indices had to be mapped such that the features of the corresponding points were "conected".

They are not the indices of the points from the point cloud. 

If you want to generate your own data you just need to ensure that for each iteration of the loop in L15
saveDatatoTFRecord.py file the SDV features that you are imputing to X and Y (L:18,19) are othe SDV features of the corresponding points. If you do that it should be fine

**Comment by zgojcic** [comment]
Closed due to inactivity. If you have any other questions please open a new issue.
