### ISSUE TITLE
Training raise OutOfRangeError

### ISSUE THREAD

**Issue by Jarrome** [zgojcic/3DSmoothNet#27]
Hi, Gojcic, I attempt to run your training script and raise some error.

```
OutOfRangeError (see above for traceback): End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,16,16,16,1], [?,16,16,16,1]], output_types=[DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
         [[Node: IteratorGetNext/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_55_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```
I unpack the training data under ./data/train/trainingData3DMatch .
Do you have any idea where is the problem?

**Comment by zgojcic** [comment]
Hi, 

tensorflow raises this error when the end of the dataset is reached. Are you sure that the path to the data is correct? There should be a console print out 'Number of training files: xxx' what is xxx in your case? 


You can also run it in debug mode and try to check what is in the 'iterator' (check /core/network.py L. 97) 

Cheers,
Zan

**Comment by Jarrome** [comment]
Ah, Thank you, Gojcic. 

```
# ./core/network.py:76
training_data_files = glob.glob(self.config.training_data_folder + '*.tfrecord')
```

should be

```
training_data_files = glob.glob(self.config.training_data_folder + '/*.tfrecord')
```
