### ISSUE TITLE
double free or corruption (out)

### ISSUE THREAD

**Issue by zhenglongyu** [zgojcic/3DSmoothNet#33]
When I run "./3DSmoothNet -f myfile -o /data/test/output", I got "double free or corruption" error:

"Config parameters successfully read in!! 

File: ./data/demo/cloud_bin_0.ply
Number of Points: 258342
Size of the voxel grid: 0.3
Number of Voxels: 16
Smoothing Kernel: 1.75
Number of keypoints:47596

Starting SDV computation!
4 threads will be used!!
Initialize the point to the descriptor for each thread used
sphere_neighbors is sphere_neighbors is 1313sphere_neighbors is sphere_neighbors is 
1341
13981367

counter_voxel is4096
counter_voxel is4096
counter_voxel is4096
counter_voxel is4096
double free or corruption (out)
Aborted (core dumped)"

Could you please tell me how to fix it?

**Comment by Leong1230** [comment]
Hi, have you solved the problem？ I run: python3 main_cnn.py --run_mode test --output_dim
but get error: Bus error (core dumped)
![image](https://user-images.githubusercontent.com/44676836/81373391-4415ef00-912f-11ea-817c-64ccd8541f62.png)
Can anyone help me with this? Thank you every much!

**Comment by zgojcic** [comment]
The original problem in this issue was solved by using it on ubuntu 16.04 instead of 18.04 (this is not the actual reason because I have used it on 18.04 as well). Can you provide a bit more information about your system?

**Comment by Leong1230** [comment]
Thank you for your attention！I ran on Ubuntu 18.04, CUDA 10.0, cuDNN 7.5, python 3.5, tenforflow 1.1
what is the suitable version for cuda and cudnn, is it 9.0 and 7 respectively?

**Comment by zgojcic** [comment]
it seems that this error actually already appears in the c++ part of the  code which is not based on cuda, so it should not matter. Did the PCL and 3DSmoothNet c++ part compile without any errors?

**Comment by Leong1230** [comment]
It seems that the versions of cudnn, cuda and tendorflow should be compatible with each other. I found that I have accidentally switched environments after compiling. It works perfectly now. Thank you very much for your reply and email!!!

**Comment by zgojcic** [comment]
Thanks for the update. If you have any other question, please open a new issue.
