### ISSUE TITLE
Extract point-wise feature from simple objects

### ISSUE THREAD

**Issue by MegaYEye** [zgojcic/3DSmoothNet#36]
Hi,

I have tried that the network can extract very nice features from large scenes, but when it scales down to small objects, the extracted features are the same for all points. May I get some ideas about the possible reason? 

I have tried to modify parameters for generating SDV. but the problem remains. I am attaching the point cloud file I used:
[point_cloud.zip](https://github.com/zgojcic/3DSmoothNet/files/5110286/point_cloud.zip)

Thanks for your attention!

**Comment by zgojcic** [comment]
Hi MegaYEye, 

I have tried to compute the 3DSmoothNet features with the point cloud you have provided and it seems that the ply format is somehow different and can therefore not be correctly imported by pcl that we use in c++ code. This results in all descriptors being the same. 

A simple solution is opening the ply file in cloudcompare and saving it again as a ply (binary). When you then run the inference with this "new" point cloud, everything work just fine. 

Hope that this help,

Cheers
Zan
