### ISSUE TITLE
About LRF computation...

### ISSUE THREAD

**Issue by jycc1991** [zgojcic/3DSmoothNet#37]
In core.cpp line 326,the source code is: toldiComputeZaxis(sphere_neighbor_z, z_axis, point_dst);
why use sphere_neighbor_z instead of sphere_neighbor?

**Comment by zgojcic** [comment]
Hi, 

this is a left over from the original TOLDI source code. In their implementation they use a three time smaller radius for the computation of the z-axis. As is denoted in our paper we use all the points also for the z axis.

"In contrast to [43], where only points within the distance 1/3*rLRF are used, we approximate the sample covariance matrix Σ˜ S using all the points pi ∈ S"

In our case therefore the code could be optimized as the computation of the  sphere_neighbor_z is not necessary as it is the same as  sphere_neighbor.

Thanks for reporting this, I will fix it when I find time. 

Best
Zan
I
