### ISSUE TITLE
The problem of running demo.py

### ISSUE THREAD

**Issue by RainbowSun1102** [zgojcic/3DSmoothNet#4]
Hi, Prof. Gojcic and Prof. Zhou

Nice work and thank you for your code.

I run demo.py according to your website and get different results as following. Are the results OK? I wonder whether the different results are caused by installing PCL abnormally?

Initial State:
![图片](https://user-images.githubusercontent.com/45990628/60178625-8e132080-984e-11e9-8865-59aa805824c8.png)

Registration Result:
![图片](https://user-images.githubusercontent.com/45990628/60178651-a08d5a00-984e-11e9-9bc9-9bb6b0d0d7d4.png)

Thank you for your time and attention.

Rainbow

**Comment by zgojcic** [comment]
Hi Rainbow,

thank you for your message. It seems that the results are the same but you have just not rotated the view of the point clouds. You can do that by click-drag in the display window. 

Best, 

Zan

**Comment by RainbowSun1102** [comment]
Hi Prof. Zan

Thank you for your reply.

Yep. I try to click-drag. It is the same with you. Sorry about it. It is my first time to use open3d library. :-)

Best wishes, 

Rainbow

**Comment by zgojcic** [comment]
No problem, we should have included the same view as the demo outputs :)  

Best regards

Zan
