### ISSUE TITLE
demo with ETH

### ISSUE THREAD

**Issue by humanpose1** [zgojcic/3DSmoothNet#40]
Hi, 
Could you make a demo with ETH dataset, to show how your entire pipeline can generalize well on ETH (as in https://github.com/fabiopoiesi/dip/ ) ?

Thanks a lot in advance !

Best

**Comment by zgojcic** [comment]
We will not provide the demo but the 3DMatch one can easily be adapted, i.e. you only need to change the path to the input point clouds and the parameters in accordance with the paper.

**Comment by surabhi96** [comment]
I was trying to do the same. I was seeing the input parameters for the ETH dataset in the paper. As per my understanding, inputs would be -r "0.28" -n "16" -h "1.00". Is my understanding correct? I was applying the same set of configuration to find the transform matrix for my custom data. But I am getting a unity transform out of RANSAC. What could I be missing?
