### ISSUE TITLE
Key points from 3DSparseMatch dataset

### ISSUE THREAD

**Issue by yukailin-git** [zgojcic/3DSmoothNet#45]
Dear Author,
I wonder know how to extract those keypoints with indices in the 3DSparsematch dataset.
What is the method you use or just random pick up 5000 points from point cloud?

Thank you so much.
Best regards,
Yu-Kai Lin.

**Comment by HOUYONGKUO** [comment]
Hello.
I have a similar problem.
How do I use my own data (only two '*.ply' files, without keypoints ) for registration instead of the data from the 3DMatch dataset?

**Comment by zgojcic** [comment]
Hi, 

we have just used basic random sampling using numpy.
