### ISSUE TITLE
Cuda and cudnn version

### ISSUE THREAD

**Issue by yukailin-git** [zgojcic/3DSmoothNet#46]
Dear Author,
I wonder know which cuda and cudnn version you use in this project.

Thank you so much.
Best regards,
Yu-Kai Lin.

**Comment by MaryAnnZ** [comment]
I set up a docker image for compiling and running 3DSmoothNet. 
The base image of my environment os `nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04`

**Comment by zgojcic** [comment]
Thank you @MaryAnnZ, I will reference this docker in the README file.
