### ISSUE TITLE
compile cpp file

### ISSUE THREAD

**Issue by fyang064** [zgojcic/3DSmoothNet#47]
Hello,

I'm wondering which version of the pcl library you used in the project. Since I came across a error when I trying to compile the cpp file following your instructions.
![image](https://user-images.githubusercontent.com/44177668/126736385-1ff5ae87-defd-4035-96cb-435f5b00ba08.png)
And I checked online and found that PointXYZ is a struct member of the pcl 1.12, but I'm not sure it is the reason that the cpp file cannot be made.

In addition, the "glob3" package in the requirements.txt cannot be installed via pip. Looking forward to hearing from you!

Thanks,
Felix

**Comment by MaryAnnZ** [comment]
I had the same issue with glob3 so I install glob2 instead and it seems to work

**Comment by ivagavran314** [comment]
Found this issue as well.
Fixed by adding missing imports...

core/core.h:
#include <pcl/impl/point_types.hpp>

main.cpp:
#include "boost/filesystem.hpp"
