### ISSUE TITLE
Registration problem

### ISSUE THREAD

**Issue by fyang064** [zgojcic/3DSmoothNet#48]
Hello,

I followed your instruction and ran your demo code based on my own data, however, the registration result is not good. I applied simple transformation matrix on the original point sets and used the original one to register the transformed one. However,  after running the 3DSmoothNet,  it shows that registration::RegistrationResult with fitness = 0.000000, inlier_rmse = 0.000000, and correspondence_set size of 0. I have no idea what's wrong with my process and the data. 
![image](https://user-images.githubusercontent.com/44177668/129412046-6165a889-8d0c-4542-97a6-f3b294e69756.png)

Looking forward to your answer, thanks a lot!

Felix

**Comment by zgojcic** [comment]
Hi, 

I think it might be the scale of the point clouds that you are using. The SDV computation runs very fast, which could mean that very little or no points are located in the neighborhood.
