### ISSUE TITLE
Building issue, flann::Matrix

### ISSUE THREAD

**Issue by Karltlbm** [zgojcic/3DSmoothNet#5]
Hi ! 

Thank you for sharing this work, I am interested to use it for my internship of 3D reconstruction.

I am having an issue in the building process,

the $make command gives me an error about flann :

```
In file included from /home/karlmontalban/dev/3DSmoothNet/main.cpp:13:
/home/karlmontalban/dev/3DSmoothNet/core/core.h:38:8: error: « Matrix » dans l'espace de noms « flann » ne nomme pas un type de patron
 flann::Matrix<float> initializeGridMatrix(const int n, float x_step, float y_step, float z_step);
(....)
```

I have installed flann on my virtual env and I have version 1.8 so I don't understand what is going on...

Any idea ?

**Comment by zgojcic** [comment]
Hei, 

thanks for your message. It seems that flann is either not installed properly or cannot be found by the cmake. 

Could you maybe run cmake-gui and make sure that the path to flann is correctly recognized? If this does not help, could you please provide a bit more information about your operating system and versions of the dependencies?

Best,

Zan

**Comment by Karltlbm** [comment]
I have this while cmake command:

```
--   Found flann, version 1.8.4
-- Found FLANN: /usr/lib64/libflann_cpp.so  
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- LIBUSB_1_LIBRARY (missing: LIBUSB_1_INCLUDE_DIR) 
** WARNING ** io features related to libusb-1.0 will be disabled
```

So I suppose that flann is found.

But ccmake shows that flann_dir is not found ...

I am on fedora 29 and 
`Le paquet flann-1.8.4-18.fc29.x86_64 est déjà installé.`

**Comment by Karltlbm** [comment]
Yes haha, this was easy, thanks !

**Comment by zgojcic** [comment]
It seems this is operating system or compiler specfic. On ubuntu it runs without including flann.h. @qq456cvb I will try if this also works on ubuntu and will accept the pull-request if it woks. 

Anyways, thank you for your help!!

Best

Zan
