### ISSUE TITLE
error compling main.cpp

### ISSUE THREAD

**Issue by sabrabano0** [zgojcic/3DSmoothNet#53]
Severity	Code	Description	Project	Path	File	Line	Source	Suppression State
Error	C2039	'PointXYZ': is not a member of 'pcl'	3DSmoothNet	D:\freelance\3DSmoothNet-master\core	D:\freelance\3DSmoothNet-master\core\core.h	7	Build	

i configure and generate this project after installing pcl1.12.0
but I gat this error

**Comment by zgojcic** [comment]
Hi sabrabano0, 

this is due to the change in the pcl API, please check https://github.com/zgojcic/3DSmoothNet/issues/47#issuecomment-902195418 for more information.
