### ISSUE TITLE
demo.py fail, no such file ...

### ISSUE THREAD

**Issue by Karltlbm** [zgojcic/3DSmoothNet#7]
Launching demo:

It fails when trying to find these files

```
# Load the descriptors and estimate the transformation parameters using RANSAC
reference_desc = np.load('./data/demo/32_dim/cloud_bin_0.ply_0.150000_16_1.750000_3DSmoothNet.npz')
reference_desc = reference_desc['data']


test_desc = np.load('./data/demo/32_dim/cloud_bin_1.ply_0.150000_16_1.750000_3DSmoothNet.npz')
test_desc = test_desc['data']
```

What are these files for ? There are not in the /data/demo directory ...

`FileNotFoundError: [Errno 2] No such file or directory: './data/demo/32_dim/cloud_bin_0.ply_0.150000_16_1.750000_3DSmoothNet.npz'`

**Comment by zgojcic** [comment]
These are the 3DSmoohNet descriptors that should be computed when running the demo.py.

Specifically, this should happen when the lines 
"
# Run the inference as shell 
args = "python main_cnn.py --run_mode=test --evaluate_input_folder=./data/demo/sdv/  --evaluate_output_folder=./data/demo"
subprocess.call(args, shell=True)

print('Inference completed perform nearest neighbor search and registration')
"

of the demo.py are carried out. 

Can you check if the input_parametrization was carried out sucsesfully? There should be a folder ./data/demo/sdv/ created and should contain some files.

**Comment by Karltlbm** [comment]
Ok so actually the folder doesn't exist

`Evaluate input data folder ./data/demo/sdv/ does not exist.`

If I add it manually, same issue:

```
Loaded saved model ./models/32_dim/3DSmoothNet_32_dim.ckpt.
Inference completed perform nearest neighbor search and registration
Traceback (most recent call last):
  File "demo.py", line 78, in <module>
    reference_desc = np.load('./data/demo/32_dim/cloud_bin_0.ply_0.150000_16_1.750000_3DSmoothNet.npz')
  File "/usr/lib64/python3.7/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/demo/32_dim/cloud_bin_0.ply_0.150000_16_1.750000_3DSmoothNet.npz'
```

**Comment by zgojcic** [comment]
You cannot just create the folder. The folder should be created when the smoothed-density value voxel grid is computed in the following lines of the demo.py code:

"
for i in range(0,len(point_cloud_files)):
    args = "./3DSmoothNet -f " + point_cloud_files[i] + " -k " + keypoints_files[i] +  " -o ./data/demo/sdv/"
    subprocess.call(args, shell=True)

print('Input parametrization complete. Start inference')
"
You should make sure that all the paths are correct and that you have both point clouds and keypoint files in the ./demo/data/ folder.

**Comment by Karltlbm** [comment]
Ok my bad it didn't work because I created a build folder for compilation where the execuatble was...
Thanks for your help !
