### ISSUE TITLE
3Dsmooth on own data, proccess killed and no keypoints

### ISSUE THREAD

**Issue by Karltlbm** [zgojcic/3DSmoothNet#8]
I am now trying to use 3DsmoothNet with my own data.
I have two 500 000 points ply files of the same scene, can size be a problem ?

I launched the executable ./3DSmoothNet on one of my pointcloud. Result is:

```
Config parameters successfully read in!! 

File: ../data/raw_point_clouds/riverside_lidar.ply
Number of Points: 442860
Size of the voxel grid: 0.3
Number of Voxels: 16
Smoothing Kernel: 1.75
Number of keypoints:442860

Less then ten points in the neighborhood!!!
Less then ten points in the neighborhood!!!
Less then ten points in the neighborhood!!!
Less then ten points in the neighborhood!!!
(..................)
Less then ten points in the neighborhood!!!
Less then ten points in the neighborhood!!!
Starting SDV computation!
8 threads will be used!!
Killed
```

Do you know what have hapenned ?

**Comment by zgojcic** [comment]
You are computing the sdv values for all the point and probably do not have enough RAM. There are some memory leaks in the code that I will update in the upcoming days but for processing 400k point you will still probably need 32GB of RAM

**Comment by zgojcic** [comment]
SVD with number of voxels 16 is a 4096 dimensional vector that has to be saved, so you have a matrix of float with dimensions 442860X4096

**Comment by zgojcic** [comment]
It also seems that the resolution of you point cloud is not so high (warnings that less than 10 points are in the neighborhood) so you should maybe increase the size of the voxel grid (support radius)

**Comment by Karltlbm** [comment]
Thanks for your answers !
I filtered my pointclouds, change the number of voxels and the size of them. 
```
Number of Points: 100000
Size of the voxel grid: 0.6
Number of Voxels: 10
Smoothing Kernel: 1.75
Number of keypoints:100000
```
This created a csv file for each pc .

Then I want to run main_cnn.py --run_mode=test on these data.
There seems to be an issue with the size of the arrays:
```
/dev/3DSmoothNet/core/network.py", line 308, in test
    evaluation_features = np.fromfile(file, dtype=np.float32).reshape(-1, self.config.input_dim)
ValueError: cannot reshape array of size 100000000 into shape (4096)
```

How can I size the csv files for my needs ? Why 100000000 ?

**Comment by caifazhou** [comment]
the number of voxel should be 16. This is number that we have used in the paper and the default input size of the neural network is 16*16*16.

**Comment by caifazhou** [comment]
@Karltlbm As for the keypoints, the proposed model can compute the feature descriptor for all the points. So that we normally do not specify the keypoints. If the index of the keypoints is not specified, the feature descriptor for all points will be computed.

**Comment by Karltlbm** [comment]
Thanks again for your answers !  I now have ply, txt and npz files !

I have an issue with my point clouds when it is translating into an np array :
```
reference_pc_keypoints = np.asarray(reference_pc.points)[indices_ref.astype(int),:]
test_pc_keypoints = np.asarray(test_pc.points)[indices_test.astype(int),:]
```
I get this error:
```
reference_pc_keypoints = np.asarray(reference_pc.points)[indices_ref.astype(int),:]
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 100000
test_pc_keypoints = np.asarray(test_pc.points)[indices_test.astype(int),:]
IndexError: index -9223372036854775808 is out of bounds for axis 0 with size 100000
```
They both seem to not fit with this function but the index look strange. They are also the same for the 2 point clouds ...
What do you think ? Would you be interested to see the ply files ?

**Comment by zgojcic** [comment]
This should be the keypoint files. If you have .ply files and keypoint files you can send them to zan.gojcic@geod.baug.ethz.ch and I will have a look when I find some time

**Comment by Karltlbm** [comment]
To use SmoothNet with my own data:

- Run 3DSMoothNet executable with own point clouds files located in /data/raw_point_clouds/
--> sdv voxel grid files should be created at /data/sdv_voxel_grid
- Copy the sdv files into /data/evaluate/input_data
- Run `python main_cnn.py --run_mode test --output_dim 128`
--> descriptors are created in /data/evaluate/output_data

Then I used the demo python code but made small modifications. In the demo, keypoints are already provided. I didn't have keypoints so in the ./3DSmoothNet I used the default option (-k 0) which makes everypoint a keypoint: 
- Comment everything about keypoints
- replace ref_key and test_key by original pointclouds (all points are used)

The result was satifsaying, not so slow considering the lack of keypoints and the alignment is good, considering the noise of the pointcloud and the different scale between them. 

```
point_cloud_files = ['/3DSmoothNet/data/raw_point_clouds/pointcloud1.ply',
                     '3DSmoothNet/data/raw_point_clouds/pointcloud2.ply']

# Load the descriptors and estimate the transformation parameters using RANSAC
reference_desc = np.load('3DSmoothNet/data/evaluate/output_data/128_dim/pointcloud1.ply_0.300000_16_1.750000_3DSmoothNet.npz')
reference_desc = reference_desc['data']

test_desc = np.load('3DSmoothNet/data/evaluate/output_data/128_dim/pointcloud1.ply_0.300000_16_1.750000_3DSmoothNet.npz')
test_desc = test_desc['data']

# Save as open3d feature
ref = open3d.registration.Feature()
ref.data = reference_desc.T

test = open3d.registration.Feature()
test.data = test_desc.T

# Load point clouds
reference_pc = read_point_cloud(point_cloud_files[0])
test_pc = read_point_cloud(point_cloud_files[1])

#NO KEYPOINTS
ref_key = reference_pc
test_key = test_pc

result_ransac = execute_global_registration(ref_key, test_key,
            ref, test, 0.05)

# First plot the original state of the point clouds
draw_registration_result(reference_pc, test_pc, np.identity(4))

# Plot point clouds after registration
print(result_ransac)
draw_registration_result(reference_pc, test_pc,
            result_ransac.transformation)
```
Some pictures of the result. Thanks for you work guys !

![smoothnet1](https://user-images.githubusercontent.com/49477491/61639669-3f657480-ac9c-11e9-9c74-601cc9d6df3a.png)
![smoothnet2](https://user-images.githubusercontent.com/49477491/61639670-3ffe0b00-ac9c-11e9-96ab-51277ab63c72.png)
![smoothnet3](https://user-images.githubusercontent.com/49477491/61639671-3ffe0b00-ac9c-11e9-84b2-7aeb4f1623d4.png)
![smoothnet4](https://user-images.githubusercontent.com/49477491/61639672-3ffe0b00-ac9c-11e9-80c2-137901239f17.png)
![smoothnet5](https://user-images.githubusercontent.com/49477491/61639673-3ffe0b00-ac9c-11e9-8d26-39e31e6263e6.png)

**Comment by surabhi96** [comment]
@Karltlbm Thanks for sharing! Where did you get the 128 dimensional checkpoint file? It doesn't seem to be there in the repository.

**Comment by zgojcic** [comment]
128 dim model is available [here](https://share.phys.ethz.ch/~gsg/3DSmoothNet/models/128_dim/3DSmoothNet_model_128_dim.rar)
