### ISSUE TITLE
How long does it takes to train?

### ISSUE THREAD

**Issue by syqzdy** [zgojcic/3DSmoothNet#9]

**Comment by zgojcic** [comment]
I think it took approximately 3-4 days to train on an GeForce GTX 1080ti

**Comment by syqzdy** [comment]
> I think it took approximately 3-4 days to train on an GeForce GTX 1080ti

But I've been training for a month and I haven't finished yet,I trained on P40, using tf1.4.

**Comment by zgojcic** [comment]
And how many iterrations are that? Is the performance still improving? I have checked it now for 32-dim we trained with batch-size 256 for 472000 iterrations which was 20 epochs.

**Comment by syqzdy** [comment]
> And how many iterrations are that? Is the performance still improving? I have checked it now for 32-dim we trained with batch-size 256 for 472000 iterrations which was 20 epochs. This took exactly 4 days and 4 hours
I use too much iterations, thank you !

**Comment by zgojcic** [comment]
It is possible that the network will still improve after the 20 epochs so it should not harm the performance. I will close this issue if you have any other questions just open a new one.

best

Zan
